name: pedometer_pro
description: Pedometer & Step Detection. Get step count in a timeRange & stream live steps.
version: 0.1.0

repository: https://github.com/whevether/pedometer_2
issue_tracker: https://github.com/whevether/pedometer_2/issues
homepage: https://pub.dev/packages/pedometer_pro

topics:
  - pedometer
  - step-counter
  - step-tracker
  - fit
  - health

screenshots:
  - description: "Example App preview"
    path: assets/example_preview.png

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.keep.pedometer_pro
        pluginClass: PedometerProPlugin
      ios:
        pluginClass: PedometerProPlugin
